-- Transactional outbox: domain write and event are committed atomically, a relay publishes later.
CREATE TABLE outbox_event (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic          VARCHAR(200) NOT NULL,
    event_key      VARCHAR(500) NOT NULL,
    event_type     VARCHAR(200) NOT NULL,
    tenant_id      VARCHAR(100),
    correlation_id VARCHAR(100),
    payload        TEXT         NOT NULL,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    sent_at        TIMESTAMP WITH TIME ZONE
);
CREATE INDEX idx_outbox_unsent ON outbox_event (id) WHERE sent_at IS NULL;

-- Lease-based distributed lock: an expired lease can be taken over, so a crashed holder never blocks.
CREATE TABLE lock_lease (
    lock_key   VARCHAR(300) PRIMARY KEY,
    owner      VARCHAR(100) NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL
);

-- Idempotency-Key store for state-changing API calls.
CREATE TABLE idempotency_key (
    tenant_id     VARCHAR(100) NOT NULL,
    idem_key      VARCHAR(200) NOT NULL,
    request_hash  VARCHAR(64)  NOT NULL,
    response_json TEXT,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    PRIMARY KEY (tenant_id, idem_key)
);
